version: '3.8'

services:
  web:
    container_name: gredis-web
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
      - ./mock_data.sql:/app/mock_data.sql
    depends_on:
      - postgresql
    networks:
      - ps
    ports:
      - 8888:8888
    

  postgresql:
    image: postgres:16
    container_name: gredis-psql
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    container_name: gredis-redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    networks:
      - ps
    ports:
      - 6379:6379
    env_file:
      - .env

networks:
  ps:
